# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='name')),
                ('price', models.IntegerField(verbose_name='price')),
                ('stock', models.IntegerField(verbose_name='stock')),
            ],
        ),
    ]
