# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20171120_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(through='mainapp.CustProd', to='mainapp.Customer'),
        ),
    ]
