# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_product_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users',
        ),
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(through='mainapp.CustProd', to='mainapp.Product'),
        ),
    ]
